# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shanyuantao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acreage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acreage_name', models.CharField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'acreage',
            },
        ),
        migrations.AlterField(
            model_name='houseprice',
            name='house_price',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
